CREATE TABLE IF NOT EXISTS USERS (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(25) NOT NULL,
  password VARCHAR(100) NOT NULL,
  firstname VARCHAR(25) NOT NULL,
  lastname VARCHAR(25) NOT NULL,
  email VARCHAR(100) NOT NULL,
  office_id TINYINT DEFAULT '0',
  role VARCHAR(25) NOT NULL,
  PRIMARY KEY (id)
);
TRUNCATE USERS;
INSERT INTO USERS (username, password, firstname, lastname, email, office_id,role)
  VALUES ('admin1', 'e00cf25ad42683b3df678c61f42c6bda', 'Michael', 'Jordan', 'admin@worksap.co.jp', 0, 'ADMIN'),
         ('user1', '24c9e15e52afc47c225b757e7bee1f9d', 'Tim', 'Duncan', 'user001@worksap.co.jp', 1, 'USER');
         
CREATE TABLE IF NOT EXISTS OFFICES (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name varchar(25),
  PRIMARY KEY (id)
);
TRUNCATE OFFICES;
INSERT INTO OFFICES (name) VALUES ('Tokyo'), ('Shanghai'), ('Singapore'), ('Osaka');

CREATE TABLE IF NOT EXISTS PRODUCTS (
	id INT(11) NOT NULL AUTO_INCREMENT,
	product_name VARCHAR(25) NOT NULL,
	first_category TINYINT NOT NULL,
	second_category TINYINT NOT NULL,
	overview VARCHAR(255),
	technology VARCHAR(255),
	specification VARCHAR(255),
	price INT(11),
	PRIMARY KEY (id)
);

TRUNCATE PRODUCTS;

CREATE TABLE IF NOT EXISTS IMAGES (
	id INT(11) NOT NULL AUTO_INCREMENT,
	product_id INT(11) NOT NULL,
	image_file_url VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);
TRUNCATE IMAGES;

CREATE TABLE IF NOT EXISTS DOCUMENTS (
	id INT(11) NOT NULL AUTO_INCREMENT,
	product_id INT(11) NOT NULL,
	doc_file_url VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

TRUNCATE DOCUMENTS;

CREATE TABLE IF NOT EXISTS CATEGORYONE (
	id INT(11) NOT NULL AUTO_INCREMENT,
	categoryone_name VARCHAR(25) NOT NULL,
	PRIMARY KEY (id)
);
TRUNCATE CATEGORYONE;


CREATE TABLE IF NOT EXISTS CATEGORYONE (
	id INT(11) NOT NULL AUTO_INCREMENT,
	categorytwo_name VARCHAR(25) NOT NULL,
	categoryone_id INT(11) NOT NULL,
	PRIMARY KEY (id)
);
TRUNCATE CATEGORYONE;